/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as GraficosRouteImport } from './routes/graficos'
import { Route as PecasRouteImport } from './routes/pecas'
import { Route as RelatorioRouteImport } from './routes/relatorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const GraficosRoute = GraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasRoute = PecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentos': typeof DocumentosRoute
  '/graficos': typeof GraficosRoute
  '/pecas': typeof PecasRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentos': typeof DocumentosRoute
  '/graficos': typeof GraficosRoute
  '/pecas': typeof PecasRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentos': typeof DocumentosRoute
  '/graficos': typeof GraficosRoute
  '/pecas': typeof PecasRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/documentos' | '/graficos' | '/pecas' | '/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/documentos' | '/graficos' | '/pecas' | '/relatorio'
  id: '__root__' | '/' | '/documentos' | '/graficos' | '/pecas' | '/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentosRoute: typeof DocumentosRoute
  GraficosRoute: typeof GraficosRoute
  PecasRoute: typeof PecasRoute
  RelatorioRoute: typeof RelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graficos': {
      id: '/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof GraficosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas': {
      id: '/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof PecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentosRoute: DocumentosRoute,
  GraficosRoute: GraficosRoute,
  PecasRoute: PecasRoute,
  RelatorioRoute: RelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
